START TRANSACTION;

CREATE TABLE IF NOT EXISTS produccion_contrato_detalle (
    id INT AUTO_INCREMENT PRIMARY KEY,
    contrato_paciente_id BIGINT UNSIGNED NOT NULL,
    agenda_evento_id BIGINT UNSIGNED NOT NULL,
    consulta_id INT NULL,
    paciente_id INT NOT NULL,
    medico_id INT NULL,
    servicio_tipo VARCHAR(50) NOT NULL,
    servicio_id INT NOT NULL,
    servicio_nombre VARCHAR(255) NOT NULL,
    fecha_atencion DATETIME NOT NULL,
    cantidad DECIMAL(10,2) NOT NULL DEFAULT 1.00,
    monto_lista_referencial DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    monto_reconocido DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    estado_financiero ENUM('pendiente_liquidar', 'liquidado', 'anulado') NOT NULL DEFAULT 'pendiente_liquidar',
    modo_cobertura ENUM('contrato', 'extra') NOT NULL DEFAULT 'contrato',
    liquidado_en DATETIME NULL,
    liquidado_por INT NULL,
    created_by INT NULL,
    updated_by INT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY ux_pcd_evento_servicio (agenda_evento_id, servicio_tipo, servicio_id),
    KEY idx_pcd_contrato_estado (contrato_paciente_id, estado_financiero),
    KEY idx_pcd_fecha_atencion (fecha_atencion),
    KEY idx_pcd_medico (medico_id),
    KEY idx_pcd_consulta (consulta_id),
    CONSTRAINT fk_pcd_contrato_paciente FOREIGN KEY (contrato_paciente_id) REFERENCES contratos_paciente(id) ON DELETE CASCADE,
    CONSTRAINT fk_pcd_agenda_evento FOREIGN KEY (agenda_evento_id) REFERENCES agenda_contrato(id) ON DELETE CASCADE,
    CONSTRAINT fk_pcd_consulta FOREIGN KEY (consulta_id) REFERENCES consultas(id) ON DELETE SET NULL,
    CONSTRAINT fk_pcd_paciente FOREIGN KEY (paciente_id) REFERENCES pacientes(id),
    CONSTRAINT fk_pcd_medico FOREIGN KEY (medico_id) REFERENCES medicos(id) ON DELETE SET NULL,
    CONSTRAINT fk_pcd_created_by FOREIGN KEY (created_by) REFERENCES usuarios(id) ON DELETE SET NULL,
    CONSTRAINT fk_pcd_updated_by FOREIGN KEY (updated_by) REFERENCES usuarios(id) ON DELETE SET NULL,
    CONSTRAINT fk_pcd_liquidado_por FOREIGN KEY (liquidado_por) REFERENCES usuarios(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

COMMIT;
