-- Migracion hc_templates desde DESARROLLO a PRODUCCION
-- Generado automaticamente: 2026-04-08 12:14:25
START TRANSACTION;

CREATE TABLE IF NOT EXISTS hc_templates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  template_id VARCHAR(100) NOT NULL,
  version VARCHAR(50) NOT NULL,
  nombre VARCHAR(150) NOT NULL,
  schema_version VARCHAR(20) NOT NULL DEFAULT '2.0',
  source VARCHAR(50) NOT NULL DEFAULT 'clinica_override',
  clinic_key VARCHAR(120) NULL,
  schema_json LONGTEXT NOT NULL,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_hc_templates_unique (template_id, version, clinic_key),
  KEY idx_hc_templates_lookup (template_id, activo, clinic_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO hc_templates (template_id, version, nombre, schema_version, source, clinic_key, schema_json, activo) VALUES ('ginecologia', '2026.04.01', 'Ginecologia', '2.0', 'clinica_override', 'femcare', '{\"sections\":{\"g_obst\":{\"g\":{\"type\":\"text\",\"width\":\"quarter\",\"rows\":2,\"options\":[],\"break_after\":false},\"p\":{\"type\":\"text\",\"width\":\"quarter\",\"rows\":2,\"options\":[],\"break_after\":true},\"g1\":{\"type\":\"text\",\"width\":\"quarter\",\"rows\":2,\"options\":[],\"break_after\":false},\"g2\":{\"type\":\"text\",\"width\":\"quarter\",\"rows\":2,\"options\":[],\"break_after\":false},\"g3\":{\"type\":\"text\",\"width\":\"quarter\",\"rows\":2,\"options\":[],\"break_after\":false},\"g4\":{\"type\":\"text\",\"width\":\"quarter\",\"rows\":2,\"options\":[],\"break_after\":false},\"fur\":{\"type\":\"text\",\"width\":\"quarter\",\"rows\":2,\"options\":[],\"break_after\":false},\"rc\":{\"type\":\"text\",\"width\":\"quarter\",\"rows\":2,\"options\":[],\"break_after\":false},\"mac\":{\"type\":\"text\",\"width\":\"quarter\",\"rows\":2,\"options\":[],\"break_after\":false},\"pap\":{\"type\":\"text\",\"width\":\"quarter\",\"rows\":2,\"options\":[],\"break_after\":false},\"irs\":{\"type\":\"text\",\"width\":\"quarter\",\"rows\":2,\"options\":[],\"break_after\":false},\"nps\":{\"type\":\"text\",\"width\":\"quarter\",\"rows\":2,\"options\":[],\"break_after\":true},\"antecedentes_personales\":{\"type\":\"textarea\",\"width\":\"full\",\"rows\":2,\"options\":[],\"break_after\":true},\"antecedentes_quirurgicos\":{\"type\":\"textarea\",\"width\":\"full\",\"rows\":2,\"options\":[],\"break_after\":true},\"antecedentes_alergicos\":{\"type\":\"textarea\",\"width\":\"full\",\"rows\":2,\"options\":[],\"break_after\":true},\"antecedentes_familiares\":{\"type\":\"textarea\",\"width\":\"full\",\"rows\":2,\"options\":[],\"break_after\":true},\"motivo_de_consulta\":{\"type\":\"textarea\",\"width\":\"full\",\"rows\":4,\"options\":[],\"break_after\":false}},\"al_examen_fisico\":{\"totax\":{\"type\":\"textarea\",\"width\":\"full\",\"rows\":2,\"options\":[],\"break_after\":true},\"abdomen\":{\"type\":\"textarea\",\"width\":\"full\",\"rows\":3,\"options\":[],\"break_after\":true},\"gu\":{\"type\":\"textarea\",\"width\":\"full\",\"rows\":2,\"options\":[],\"break_after\":true},\"especuloscopia\":{\"type\":\"textarea\",\"width\":\"full\",\"rows\":2,\"options\":[],\"break_after\":true},\"tacto_vaginal\":{\"type\":\"textarea\",\"width\":\"full\",\"rows\":2,\"options\":[],\"break_after\":true}},\"descripciones\":{\"observacion\":{\"type\":\"textarea\",\"width\":\"half\",\"rows\":2,\"options\":[],\"break_after\":false}}}}', 1) ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), schema_version=VALUES(schema_version), source=VALUES(source), schema_json=VALUES(schema_json), activo=VALUES(activo);
INSERT INTO hc_templates (template_id, version, nombre, schema_version, source, clinic_key, schema_json, activo) VALUES ('medicina_general', '2026.04.01', 'Medicina General', '2.0', 'clinica_override', NULL, '{\"sections\":{\"anamnesis\":{\"tiempo_enfermedad\":\"\",\"forma_inicio\":\"\",\"curso\":\"\"},\"antecedentes\":{\"antecedentes\":\"\"},\"examen_fisico\":{\"examen_fisico\":\"\"},\"plan\":{\"tratamiento\":\"\"}}}', 1) ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), schema_version=VALUES(schema_version), source=VALUES(source), schema_json=VALUES(schema_json), activo=VALUES(activo);
INSERT INTO hc_templates (template_id, version, nombre, schema_version, source, clinic_key, schema_json, activo) VALUES ('pediatria', '2026.04.01', 'Pediatria', '2.0', 'clinica_override', 'cardiovida', '{\"sections\":{\"anamnesis\":{\"tiempo_enfermedad\":\"\",\"forma_inicio\":\"\",\"curso\":\"\"},\"antecedentes\":{\"vacunas_completas\":\"\",\"alergias\":\"\",\"antecedentes\":\"\"},\"crecimiento\":{\"peso\":\"\",\"talla\":\"\",\"imc\":\"\"},\"plan\":{\"tratamiento\":\"\"}}}', 1) ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), schema_version=VALUES(schema_version), source=VALUES(source), schema_json=VALUES(schema_json), activo=VALUES(activo);
INSERT INTO hc_templates (template_id, version, nombre, schema_version, source, clinic_key, schema_json, activo) VALUES ('plantilla_202604022109', '2026.04.01', 'Psicólogo', '2.0', 'clinica_override', 'cardiovida', '{\"sections\":{\"motivo_consulta_psicologica\":{\"descripcion\":{\"type\":\"textarea\",\"width\":\"half\",\"rows\":2,\"options\":[],\"break_after\":false}},\"anamnesis\":{\"tiempo_enfermedad\":{\"type\":\"textarea\",\"width\":\"half\",\"rows\":2,\"options\":[],\"break_after\":false}},\"examen_fisico\":{\"examen_general\":{\"type\":\"textarea\",\"width\":\"half\",\"rows\":2,\"options\":[],\"break_after\":false}}}}', 1) ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), schema_version=VALUES(schema_version), source=VALUES(source), schema_json=VALUES(schema_json), activo=VALUES(activo);

COMMIT;
