-- Tabla para almacenar los códigos CIE10
CREATE TABLE cie10 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    codigo VARCHAR(10) NOT NULL UNIQUE,
    nombre VARCHAR(500) NOT NULL,
    categoria VARCHAR(100),
    subcategoria VARCHAR(100),
    descripcion TEXT,
    activo TINYINT(1) DEFAULT 1,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_codigo (codigo),
    INDEX idx_nombre (nombre),
    INDEX idx_categoria (categoria),
    FULLTEXT(nombre, descripcion)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insertar algunos datos de ejemplo de CIE10 más comunes
INSERT INTO cie10 (codigo, nombre, categoria, subcategoria, descripcion) VALUES
-- Enfermedades infecciosas y parasitarias (A00-B99)
('A00.0', 'Cólera debido a Vibrio cholerae 01, biotipo cholerae', 'Enfermedades infecciosas', 'Enfermedades intestinales infecciosas', 'Infección por Vibrio cholerae'),
('A00.1', 'Cólera debido a Vibrio cholerae 01, biotipo El Tor', 'Enfermedades infecciosas', 'Enfermedades intestinales infecciosas', 'Infección por Vibrio cholerae'),
('A00.9', 'Cólera, no especificado', 'Enfermedades infecciosas', 'Enfermedades intestinales infecciosas', 'Infección por Vibrio cholerae'),
('A01.0', 'Fiebre tifoidea', 'Enfermedades infecciosas', 'Enfermedades intestinales infecciosas', 'Infección por Salmonella typhi'),
('A01.1', 'Fiebre paratifoidea A', 'Enfermedades infecciosas', 'Enfermedades intestinales infecciosas', 'Infección por Salmonella paratyphi A'),
('A01.2', 'Fiebre paratifoidea B', 'Enfermedades infecciosas', 'Enfermedades intestinales infecciosas', 'Infección por Salmonella paratyphi B'),
('A01.3', 'Fiebre paratifoidea C', 'Enfermedades infecciosas', 'Enfermedades intestinales infecciosas', 'Infección por Salmonella paratyphi C'),
('A01.4', 'Fiebre paratifoidea, no especificada', 'Enfermedades infecciosas', 'Enfermedades intestinales infecciosas', 'Infección por Salmonella paratyphi'),
('A09', 'Diarrea y gastroenteritis de presunto origen infeccioso', 'Enfermedades infecciosas', 'Enfermedades intestinales infecciosas', 'Gastroenteritis infecciosa'),

-- Enfermedades endocrinas (E00-E89)
('E10.0', 'Diabetes mellitus tipo 1 con coma', 'Enfermedades endocrinas', 'Diabetes mellitus', 'Diabetes tipo 1 con complicaciones agudas'),
('E10.1', 'Diabetes mellitus tipo 1 con cetoacidosis', 'Enfermedades endocrinas', 'Diabetes mellitus', 'Diabetes tipo 1 con complicaciones agudas'),
('E10.9', 'Diabetes mellitus tipo 1, sin complicaciones', 'Enfermedades endocrinas', 'Diabetes mellitus', 'Diabetes tipo 1 sin complicaciones'),
('E11.0', 'Diabetes mellitus tipo 2 con coma', 'Enfermedades endocrinas', 'Diabetes mellitus', 'Diabetes tipo 2 con complicaciones agudas'),
('E11.1', 'Diabetes mellitus tipo 2 con cetoacidosis', 'Enfermedades endocrinas', 'Diabetes mellitus', 'Diabetes tipo 2 con complicaciones agudas'),
('E11.9', 'Diabetes mellitus tipo 2, sin complicaciones', 'Enfermedades endocrinas', 'Diabetes mellitus', 'Diabetes tipo 2 sin complicaciones'),

-- Enfermedades del sistema circulatorio (I00-I99)
('I10', 'Hipertensión esencial (primaria)', 'Enfermedades circulatorias', 'Enfermedades hipertensivas', 'Presión arterial elevada sin causa específica'),
('I11.0', 'Enfermedad cardíaca hipertensiva con insuficiencia cardíaca (congestiva)', 'Enfermedades circulatorias', 'Enfermedades hipertensivas', 'Hipertensión con complicaciones cardíacas'),
('I11.9', 'Enfermedad cardíaca hipertensiva sin insuficiencia cardíaca (congestiva)', 'Enfermedades circulatorias', 'Enfermedades hipertensivas', 'Hipertensión con complicaciones cardíacas'),
('I20.0', 'Angina de pecho inestable', 'Enfermedades circulatorias', 'Cardiopatía isquémica', 'Dolor torácico de origen coronario'),
('I20.1', 'Angina de pecho con espasmo coronario documentado', 'Enfermedades circulatorias', 'Cardiopatía isquémica', 'Dolor torácico de origen coronario'),
('I20.8', 'Otras formas de angina de pecho', 'Enfermedades circulatorias', 'Cardiopatía isquémica', 'Dolor torácico de origen coronario'),
('I20.9', 'Angina de pecho, no especificada', 'Enfermedades circulatorias', 'Cardiopatía isquémica', 'Dolor torácico de origen coronario'),
('I21.0', 'Infarto agudo del miocardio de la pared anterior', 'Enfermedades circulatorias', 'Cardiopatía isquémica', 'Ataque al corazón'),
('I21.1', 'Infarto agudo del miocardio de la pared inferior', 'Enfermedades circulatorias', 'Cardiopatía isquémica', 'Ataque al corazón'),
('I21.9', 'Infarto agudo del miocardio, no especificado', 'Enfermedades circulatorias', 'Cardiopatía isquémica', 'Ataque al corazón'),

-- Enfermedades del sistema respiratorio (J00-J99)
('J00', 'Rinofaringitis aguda [resfriado común]', 'Enfermedades respiratorias', 'Infecciones respiratorias agudas', 'Resfriado común'),
('J01.0', 'Sinusitis maxilar aguda', 'Enfermedades respiratorias', 'Infecciones respiratorias agudas', 'Inflamación de senos paranasales'),
('J01.1', 'Sinusitis frontal aguda', 'Enfermedades respiratorias', 'Infecciones respiratorias agudas', 'Inflamación de senos paranasales'),
('J01.9', 'Sinusitis aguda, no especificada', 'Enfermedades respiratorias', 'Infecciones respiratorias agudas', 'Inflamación de senos paranasales'),
('J02.0', 'Faringitis estreptocócica', 'Enfermedades respiratorias', 'Infecciones respiratorias agudas', 'Inflamación de la faringe'),
('J02.8', 'Faringitis aguda debida a otros microorganismos especificados', 'Enfermedades respiratorias', 'Infecciones respiratorias agudas', 'Inflamación de la faringe'),
('J02.9', 'Faringitis aguda, no especificada', 'Enfermedades respiratorias', 'Infecciones respiratorias agudas', 'Inflamación de la faringe'),
('J03.0', 'Amigdalitis estreptocócica', 'Enfermedades respiratorias', 'Infecciones respiratorias agudas', 'Inflamación de las amígdalas'),
('J03.9', 'Amigdalitis aguda, no especificada', 'Enfermedades respiratorias', 'Infecciones respiratorias agudas', 'Inflamación de las amígdalas'),
('J18.0', 'Bronconeumonía, no especificada', 'Enfermedades respiratorias', 'Neumonía', 'Infección pulmonar'),
('J18.1', 'Neumonía lobar, no especificada', 'Enfermedades respiratorias', 'Neumonía', 'Infección pulmonar'),
('J18.2', 'Neumonía hipostática, no especificada', 'Enfermedades respiratorias', 'Neumonía', 'Infección pulmonar'),
('J18.8', 'Otras neumonías, microorganismo no especificado', 'Enfermedades respiratorias', 'Neumonía', 'Infección pulmonar'),
('J18.9', 'Neumonía, no especificada', 'Enfermedades respiratorias', 'Neumonía', 'Infección pulmonar'),
('J44.0', 'Enfermedad pulmonar obstructiva crónica con infección respiratoria aguda del tracto respiratorio inferior', 'Enfermedades respiratorias', 'EPOC', 'Enfermedad pulmonar obstructiva crónica'),
('J44.1', 'Enfermedad pulmonar obstructiva crónica con exacerbación aguda, no especificada', 'Enfermedades respiratorias', 'EPOC', 'Enfermedad pulmonar obstructiva crónica'),
('J44.9', 'Enfermedad pulmonar obstructiva crónica, no especificada', 'Enfermedades respiratorias', 'EPOC', 'Enfermedad pulmonar obstructiva crónica'),
('J45.0', 'Asma predominantemente alérgica', 'Enfermedades respiratorias', 'Asma', 'Enfermedad respiratoria obstructiva'),
('J45.1', 'Asma no alérgica', 'Enfermedades respiratorias', 'Asma', 'Enfermedad respiratoria obstructiva'),
('J45.8', 'Asma mixta', 'Enfermedades respiratorias', 'Asma', 'Enfermedad respiratoria obstructiva'),
('J45.9', 'Asma, no especificada', 'Enfermedades respiratorias', 'Asma', 'Enfermedad respiratoria obstructiva'),

-- Enfermedades del sistema digestivo (K00-K93)
('K21.0', 'Enfermedad por reflujo gastroesofágico con esofagitis', 'Enfermedades digestivas', 'Enfermedades del esófago', 'Reflujo gastroesofágico'),
('K21.9', 'Enfermedad por reflujo gastroesofágico sin esofagitis', 'Enfermedades digestivas', 'Enfermedades del esófago', 'Reflujo gastroesofágico'),
('K25.0', 'Úlcera gástrica aguda con hemorragia', 'Enfermedades digestivas', 'Úlcera péptica', 'Úlcera del estómago'),
('K25.1', 'Úlcera gástrica aguda con perforación', 'Enfermedades digestivas', 'Úlcera péptica', 'Úlcera del estómago'),
('K25.9', 'Úlcera gástrica, no especificada como aguda o crónica, sin hemorragia ni perforación', 'Enfermedades digestivas', 'Úlcera péptica', 'Úlcera del estómago'),
('K29.0', 'Gastritis hemorrágica aguda', 'Enfermedades digestivas', 'Gastritis y duodenitis', 'Inflamación del estómago'),
('K29.1', 'Otras gastritis agudas', 'Enfermedades digestivas', 'Gastritis y duodenitis', 'Inflamación del estómago'),
('K29.7', 'Gastritis, no especificada', 'Enfermedades digestivas', 'Gastritis y duodenitis', 'Inflamación del estómago'),
('K59.0', 'Estreñimiento', 'Enfermedades digestivas', 'Otros trastornos intestinales', 'Dificultad para defecar'),
('K59.1', 'Diarrea funcional', 'Enfermedades digestivas', 'Otros trastornos intestinales', 'Evacuaciones líquidas frecuentes'),

-- Factores que influyen en el estado de salud (Z00-Z99)
('Z00.0', 'Examen médico general', 'Factores de salud', 'Exámenes médicos', 'Chequeo de rutina'),
('Z00.1', 'Examen de rutina del niño', 'Factores de salud', 'Exámenes médicos', 'Control pediátrico'),
('Z01.0', 'Examen de los ojos y la visión', 'Factores de salud', 'Exámenes específicos', 'Evaluación oftalmológica'),
('Z01.1', 'Examen de los oídos y la audición', 'Factores de salud', 'Exámenes específicos', 'Evaluación auditiva'),
('Z10.0', 'Examen general de rutina de una subpoblación definida', 'Factores de salud', 'Exámenes de población', 'Screening poblacional'),
('Z11.0', 'Examen especial de detección de enfermedades intestinales infecciosas', 'Factores de salud', 'Screening específico', 'Detección de enfermedades'),
('Z71.1', 'Persona que consulta en nombre de otra persona', 'Factores de salud', 'Consultas especiales', 'Consulta por terceros'),
('Z71.9', 'Consejo, no especificado', 'Factores de salud', 'Consultas especiales', 'Asesoramiento médico'),

-- Síntomas y signos (R00-R99)
('R00.0', 'Taquicardia, no especificada', 'Síntomas y signos', 'Síntomas circulatorios', 'Frecuencia cardíaca elevada'),
('R00.1', 'Bradicardia, no especificada', 'Síntomas y signos', 'Síntomas circulatorios', 'Frecuencia cardíaca baja'),
('R00.2', 'Palpitaciones', 'Síntomas y signos', 'Síntomas circulatorios', 'Percepción anormal del latido cardíaco'),
('R05', 'Tos', 'Síntomas y signos', 'Síntomas respiratorios', 'Expulsión súbita y ruidosa del aire'),
('R06.0', 'Disnea', 'Síntomas y signos', 'Síntomas respiratorios', 'Dificultad para respirar'),
('R10.0', 'Abdomen agudo', 'Síntomas y signos', 'Síntomas digestivos', 'Dolor abdominal severo'),
('R10.1', 'Dolor localizado en la parte superior del abdomen', 'Síntomas y signos', 'Síntomas digestivos', 'Dolor en epigastrio'),
('R10.3', 'Dolor localizado en otras partes inferiores del abdomen', 'Síntomas y signos', 'Síntomas digestivos', 'Dolor en hipogastrio'),
('R10.4', 'Otros dolores abdominales y los no especificados', 'Síntomas y signos', 'Síntomas digestivos', 'Dolor abdominal inespecífico'),
('R50.9', 'Fiebre, no especificada', 'Síntomas y signos', 'Síntomas generales', 'Elevación de la temperatura corporal'),
('R51', 'Cefalea', 'Síntomas y signos', 'Síntomas neurológicos', 'Dolor de cabeza'),
('R53', 'Malestar y fatiga', 'Síntomas y signos', 'Síntomas generales', 'Sensación de cansancio'),
('R60.0', 'Edema localizado', 'Síntomas y signos', 'Síntomas circulatorios', 'Hinchazón localizada'),
('R60.1', 'Edema generalizado', 'Síntomas y signos', 'Síntomas circulatorios', 'Hinchazón generalizada'),
('R60.9', 'Edema, no especificado', 'Síntomas y signos', 'Síntomas circulatorios', 'Hinchazón no especificada'),

-- GASTROENTEROLOGÍA - Enfermedades digestivas adicionales (K00-K93)
('K35.0', 'Apendicitis aguda generalizada', 'Gastroenterología', 'Apendicitis', 'Inflamación aguda del apéndice cecal'),
('K35.1', 'Apendicitis aguda localizada', 'Gastroenterología', 'Apendicitis', 'Inflamación localizada del apéndice'),
('K35.9', 'Apendicitis aguda, no especificada', 'Gastroenterología', 'Apendicitis', 'Inflamación del apéndice cecal'),
('K40.0', 'Hernia inguinal bilateral, con obstrucción, sin gangrena', 'Gastroenterología', 'Hernias', 'Hernia en región inguinal'),
('K40.1', 'Hernia inguinal bilateral, con gangrena', 'Gastroenterología', 'Hernias', 'Hernia inguinal complicada'),
('K40.9', 'Hernia inguinal unilateral o no especificada, sin obstrucción ni gangrena', 'Gastroenterología', 'Hernias', 'Hernia inguinal simple'),
('K41.9', 'Hernia femoral unilateral o no especificada, sin obstrucción ni gangrena', 'Gastroenterología', 'Hernias', 'Hernia en región femoral'),
('K42.9', 'Hernia umbilical sin obstrucción ni gangrena', 'Gastroenterología', 'Hernias', 'Hernia en ombligo'),
('K43.9', 'Hernia ventral sin obstrucción ni gangrena', 'Gastroenterología', 'Hernias', 'Hernia en pared abdominal'),
('K44.0', 'Hernia diafragmática con obstrucción, sin gangrena', 'Gastroenterología', 'Hernias', 'Hernia del diafragma'),
('K44.9', 'Hernia diafragmática sin obstrucción ni gangrena', 'Gastroenterología', 'Hernias', 'Hernia hiatal'),
('K50.0', 'Enfermedad de Crohn del intestino delgado', 'Gastroenterología', 'Enfermedad inflamatoria intestinal', 'Enfermedad de Crohn'),
('K50.1', 'Enfermedad de Crohn del intestino grueso', 'Gastroenterología', 'Enfermedad inflamatoria intestinal', 'Enfermedad de Crohn'),
('K50.9', 'Enfermedad de Crohn, no especificada', 'Gastroenterología', 'Enfermedad inflamatoria intestinal', 'Enfermedad de Crohn'),
('K51.0', 'Colitis ulcerosa (crónica) pancolítica', 'Gastroenterología', 'Enfermedad inflamatoria intestinal', 'Colitis ulcerosa'),
('K51.2', 'Colitis ulcerosa (crónica) inespecífica', 'Gastroenterología', 'Enfermedad inflamatoria intestinal', 'Colitis ulcerosa'),
('K51.9', 'Colitis ulcerosa, no especificada', 'Gastroenterología', 'Enfermedad inflamatoria intestinal', 'Colitis ulcerosa'),
('K57.0', 'Enfermedad diverticular del intestino delgado con perforación y absceso', 'Gastroenterología', 'Enfermedad diverticular', 'Diverticulitis complicada'),
('K57.2', 'Enfermedad diverticular del intestino grueso con perforación y absceso', 'Gastroenterología', 'Enfermedad diverticular', 'Diverticulitis complicada'),
('K57.3', 'Enfermedad diverticular del intestino grueso sin perforación ni absceso', 'Gastroenterología', 'Enfermedad diverticular', 'Diverticulosis'),
('K57.9', 'Enfermedad diverticular de sitio no especificado sin perforación ni absceso', 'Gastroenterología', 'Enfermedad diverticular', 'Diverticulosis'),
('K58.0', 'Síndrome del intestino irritable con diarrea', 'Gastroenterología', 'Trastornos funcionales', 'Colon irritable'),
('K58.9', 'Síndrome del intestino irritable sin diarrea', 'Gastroenterología', 'Trastornos funcionales', 'Colon irritable'),
('K70.0', 'Hígado graso alcohólico', 'Gastroenterología', 'Enfermedades hepáticas', 'Hepatopatía alcohólica'),
('K70.1', 'Hepatitis alcohólica', 'Gastroenterología', 'Enfermedades hepáticas', 'Hepatopatía alcohólica'),
('K70.3', 'Cirrosis hepática alcohólica', 'Gastroenterología', 'Enfermedades hepáticas', 'Cirrosis alcohólica'),
('K71.9', 'Enfermedad hepática tóxica, no especificada', 'Gastroenterología', 'Enfermedades hepáticas', 'Hepatopatía tóxica'),
('K72.0', 'Insuficiencia hepática aguda y subaguda', 'Gastroenterología', 'Enfermedades hepáticas', 'Falla hepática'),
('K72.9', 'Insuficiencia hepática, no especificada', 'Gastroenterología', 'Enfermedades hepáticas', 'Falla hepática'),
('K73.9', 'Hepatitis crónica, no especificada', 'Gastroenterología', 'Enfermedades hepáticas', 'Hepatitis crónica'),
('K74.0', 'Fibrosis hepática', 'Gastroenterología', 'Enfermedades hepáticas', 'Fibrosis del hígado'),
('K74.6', 'Otra cirrosis hepática y la no especificada', 'Gastroenterología', 'Enfermedades hepáticas', 'Cirrosis hepática'),
('K76.0', 'Degeneración grasa del hígado, no clasificada en otra parte', 'Gastroenterología', 'Enfermedades hepáticas', 'Hígado graso'),
('K80.0', 'Cálculos de la vesícula biliar con colecistitis aguda', 'Gastroenterología', 'Enfermedades biliares', 'Colecistitis aguda'),
('K80.1', 'Cálculos de la vesícula biliar con otra colecistitis', 'Gastroenterología', 'Enfermedades biliares', 'Colecistitis crónica'),
('K80.2', 'Cálculos de la vesícula biliar sin colecistitis', 'Gastroenterología', 'Enfermedades biliares', 'Colelitiasis'),
('K83.0', 'Colangitis', 'Gastroenterología', 'Enfermedades biliares', 'Infección de vías biliares'),
('K85.0', 'Pancreatitis aguda idiopática', 'Gastroenterología', 'Enfermedades pancreáticas', 'Pancreatitis aguda'),
('K85.1', 'Pancreatitis aguda biliar', 'Gastroenterología', 'Enfermedades pancreáticas', 'Pancreatitis aguda'),
('K85.9', 'Pancreatitis aguda, no especificada', 'Gastroenterología', 'Enfermedades pancreáticas', 'Pancreatitis aguda'),
('K86.0', 'Pancreatitis crónica de origen alcohólico', 'Gastroenterología', 'Enfermedades pancreáticas', 'Pancreatitis crónica'),
('K86.1', 'Otras pancreatitis crónicas', 'Gastroenterología', 'Enfermedades pancreáticas', 'Pancreatitis crónica'),
('K92.0', 'Hematemesis', 'Gastroenterología', 'Hemorragia digestiva', 'Vómito con sangre'),
('K92.1', 'Melena', 'Gastroenterología', 'Hemorragia digestiva', 'Sangrado digestivo bajo'),
('K92.2', 'Hemorragia gastrointestinal, no especificada', 'Gastroenterología', 'Hemorragia digestiva', 'Sangrado digestivo'),

-- TRAUMATOLOGÍA - Fracturas y lesiones (S00-T88)
('S02.0', 'Fractura de la bóveda del cráneo', 'Traumatología', 'Fracturas de cráneo', 'Fractura craneal'),
('S02.1', 'Fractura de la base del cráneo', 'Traumatología', 'Fracturas de cráneo', 'Fractura de base craneal'),
('S02.4', 'Fractura de los huesos malares y maxilares', 'Traumatología', 'Fracturas faciales', 'Fractura facial'),
('S02.5', 'Fractura de los dientes', 'Traumatología', 'Fracturas faciales', 'Fractura dental'),
('S02.6', 'Fractura de la mandíbula', 'Traumatología', 'Fracturas faciales', 'Fractura mandibular'),
('S12.0', 'Fractura de la primera vértebra cervical', 'Traumatología', 'Fracturas vertebrales', 'Fractura de atlas'),
('S12.1', 'Fractura de la segunda vértebra cervical', 'Traumatología', 'Fracturas vertebrales', 'Fractura de axis'),
('S12.2', 'Fractura de otras vértebras cervicales especificadas', 'Traumatología', 'Fracturas vertebrales', 'Fractura cervical'),
('S12.9', 'Fractura del cuello, parte no especificada', 'Traumatología', 'Fracturas vertebrales', 'Fractura cervical'),
('S22.0', 'Fractura de vértebra torácica', 'Traumatología', 'Fracturas vertebrales', 'Fractura dorsal'),
('S22.1', 'Fracturas múltiples de vértebras torácicas', 'Traumatología', 'Fracturas vertebrales', 'Fracturas múltiples dorsales'),
('S22.2', 'Fractura del esternón', 'Traumatología', 'Fracturas torácicas', 'Fractura esternal'),
('S22.3', 'Fractura de costilla', 'Traumatología', 'Fracturas torácicas', 'Fractura costal'),
('S22.4', 'Fracturas múltiples de costillas', 'Traumatología', 'Fracturas torácicas', 'Fracturas costales múltiples'),
('S32.0', 'Fractura de vértebra lumbar', 'Traumatología', 'Fracturas vertebrales', 'Fractura lumbar'),
('S32.1', 'Fractura del sacro', 'Traumatología', 'Fracturas pélvicas', 'Fractura sacra'),
('S32.2', 'Fractura del coxis', 'Traumatología', 'Fracturas pélvicas', 'Fractura coccígea'),
('S32.3', 'Fractura del ilion', 'Traumatología', 'Fracturas pélvicas', 'Fractura de ilion'),
('S32.4', 'Fractura del acetábulo', 'Traumatología', 'Fracturas pélvicas', 'Fractura acetabular'),
('S32.5', 'Fractura del pubis', 'Traumatología', 'Fracturas pélvicas', 'Fractura púbica'),
('S32.8', 'Fractura de otras partes de la pelvis y de las no especificadas', 'Traumatología', 'Fracturas pélvicas', 'Fractura pélvica'),
('S42.0', 'Fractura de la clavícula', 'Traumatología', 'Fracturas de miembro superior', 'Fractura clavicular'),
('S42.1', 'Fractura del omóplato', 'Traumatología', 'Fracturas de miembro superior', 'Fractura escapular'),
('S42.2', 'Fractura del extremo superior del húmero', 'Traumatología', 'Fracturas de miembro superior', 'Fractura de húmero proximal'),
('S42.3', 'Fractura de la diáfisis del húmero', 'Traumatología', 'Fracturas de miembro superior', 'Fractura diafisaria de húmero'),
('S42.4', 'Fractura del extremo inferior del húmero', 'Traumatología', 'Fracturas de miembro superior', 'Fractura de húmero distal'),
('S52.0', 'Fractura del extremo superior del cúbito', 'Traumatología', 'Fracturas de antebrazo', 'Fractura de olécranon'),
('S52.1', 'Fractura del extremo superior del radio', 'Traumatología', 'Fracturas de antebrazo', 'Fractura de radio proximal'),
('S52.2', 'Fractura de la diáfisis del cúbito', 'Traumatología', 'Fracturas de antebrazo', 'Fractura diafisaria de cúbito'),
('S52.3', 'Fractura de la diáfisis del radio', 'Traumatología', 'Fracturas de antebrazo', 'Fractura diafisaria de radio'),
('S52.5', 'Fractura del extremo inferior del radio', 'Traumatología', 'Fracturas de antebrazo', 'Fractura de Colles'),
('S52.6', 'Fractura del extremo inferior del cúbito y del radio', 'Traumatología', 'Fracturas de antebrazo', 'Fractura de radio y cúbito distal'),
('S62.0', 'Fractura del hueso navicular (escafoides) de la mano', 'Traumatología', 'Fracturas de mano', 'Fractura de escafoides'),
('S62.1', 'Fractura de otros huesos del carpo', 'Traumatología', 'Fracturas de mano', 'Fractura carpiana'),
('S62.2', 'Fractura del primer metacarpiano', 'Traumatología', 'Fracturas de mano', 'Fractura de primer metacarpiano'),
('S62.3', 'Fractura de otros huesos metacarpianos', 'Traumatología', 'Fracturas de mano', 'Fractura metacarpiana'),
('S62.5', 'Fractura del pulgar', 'Traumatología', 'Fracturas de mano', 'Fractura de pulgar'),
('S62.6', 'Fractura de otros dedos', 'Traumatología', 'Fracturas de mano', 'Fractura de dedos'),
('S72.0', 'Fractura del cuello del fémur', 'Traumatología', 'Fracturas de miembro inferior', 'Fractura de cuello femoral'),
('S72.1', 'Fractura pertrocantérea', 'Traumatología', 'Fracturas de miembro inferior', 'Fractura pertrocantérea'),
('S72.2', 'Fractura subtrocantérea', 'Traumatología', 'Fracturas de miembro inferior', 'Fractura subtrocantérea'),
('S72.3', 'Fractura de la diáfisis del fémur', 'Traumatología', 'Fracturas de miembro inferior', 'Fractura diafisaria femoral'),
('S72.4', 'Fractura del extremo inferior del fémur', 'Traumatología', 'Fracturas de miembro inferior', 'Fractura supracondílea femoral'),
('S82.0', 'Fractura de la rótula', 'Traumatología', 'Fracturas de pierna', 'Fractura rotuliana'),
('S82.1', 'Fractura del extremo superior de la tibia', 'Traumatología', 'Fracturas de pierna', 'Fractura de meseta tibial'),
('S82.2', 'Fractura de la diáfisis de la tibia', 'Traumatología', 'Fracturas de pierna', 'Fractura diafisaria tibial'),
('S82.3', 'Fractura del extremo inferior de la tibia', 'Traumatología', 'Fracturas de pierna', 'Fractura de tibia distal'),
('S82.4', 'Fractura del peroné solamente', 'Traumatología', 'Fracturas de pierna', 'Fractura de peroné'),
('S82.5', 'Fractura del maléolo interno', 'Traumatología', 'Fracturas de tobillo', 'Fractura maleolar interna'),
('S82.6', 'Fractura del maléolo externo', 'Traumatología', 'Fracturas de tobillo', 'Fractura maleolar externa'),
('S82.8', 'Fracturas de otras partes de la pierna', 'Traumatología', 'Fracturas de pierna', 'Otras fracturas de pierna'),
('S92.0', 'Fractura del calcáneo', 'Traumatología', 'Fracturas de pie', 'Fractura del talón'),
('S92.1', 'Fractura del astrágalo', 'Traumatología', 'Fracturas de pie', 'Fractura del astrágalo'),
('S92.2', 'Fractura de otros huesos del tarso', 'Traumatología', 'Fracturas de pie', 'Fractura tarsiana'),
('S92.3', 'Fractura de los huesos del metatarso', 'Traumatología', 'Fracturas de pie', 'Fractura metatarsiana'),
('S92.4', 'Fractura del dedo gordo del pie', 'Traumatología', 'Fracturas de pie', 'Fractura del hallux'),
('S92.5', 'Fractura de otros dedos del pie', 'Traumatología', 'Fracturas de pie', 'Fractura de dedos del pie'),

-- TRAUMATOLOGÍA - Luxaciones y esguinces
('S13.0', 'Luxación traumática de vértebras cervicales', 'Traumatología', 'Luxaciones vertebrales', 'Luxación cervical'),
('S13.1', 'Luxación de disco cervical', 'Traumatología', 'Luxaciones vertebrales', 'Luxación discal cervical'),
('S23.0', 'Luxación traumática de vértebra torácica', 'Traumatología', 'Luxaciones vertebrales', 'Luxación dorsal'),
('S23.1', 'Luxación de disco torácico', 'Traumatología', 'Luxaciones vertebrales', 'Luxación discal dorsal'),
('S33.0', 'Luxación traumática de vértebra lumbar', 'Traumatología', 'Luxaciones vertebrales', 'Luxación lumbar'),
('S33.1', 'Luxación de disco lumbar', 'Traumatología', 'Luxaciones vertebrales', 'Luxación discal lumbar'),
('S43.0', 'Luxación de la articulación del hombro', 'Traumatología', 'Luxaciones de miembro superior', 'Luxación glenohumeral'),
('S43.1', 'Luxación de la articulación acromioclavicular', 'Traumatología', 'Luxaciones de miembro superior', 'Luxación acromioclavicular'),
('S53.0', 'Luxación de la cabeza del radio', 'Traumatología', 'Luxaciones de codo', 'Luxación radiocubital'),
('S53.1', 'Luxación del codo, no especificada', 'Traumatología', 'Luxaciones de codo', 'Luxación de codo'),
('S63.0', 'Luxación de la muñeca', 'Traumatología', 'Luxaciones de mano', 'Luxación radiocarpiana'),
('S63.1', 'Luxación de dedo de la mano', 'Traumatología', 'Luxaciones de mano', 'Luxación digital'),
('S73.0', 'Luxación de la cadera', 'Traumatología', 'Luxaciones de miembro inferior', 'Luxación coxofemoral'),
('S83.0', 'Luxación de la rótula', 'Traumatología', 'Luxaciones de rodilla', 'Luxación rotuliana'),
('S83.1', 'Luxación de la rodilla', 'Traumatología', 'Luxaciones de rodilla', 'Luxación tibiofemoral'),
('S93.0', 'Luxación del tobillo', 'Traumatología', 'Luxaciones de pie', 'Luxación del tobillo'),
('S93.1', 'Luxación de los dedos del pie', 'Traumatología', 'Luxaciones de pie', 'Luxación de dedos del pie'),

-- HEMATOLOGÍA - Enfermedades de la sangre y órganos hematopoyéticos (D50-D89)
('D50.0', 'Anemia por deficiencia de hierro secundaria a pérdida de sangre (crónica)', 'Hematología', 'Anemias por deficiencia de hierro', 'Anemia ferropénica por sangrado'),
('D50.1', 'Anemia sideropénica distrópica', 'Hematología', 'Anemias por deficiencia de hierro', 'Anemia por deficiencia de hierro'),
('D50.8', 'Otras anemias por deficiencia de hierro', 'Hematología', 'Anemias por deficiencia de hierro', 'Anemia ferropénica'),
('D50.9', 'Anemia por deficiencia de hierro, no especificada', 'Hematología', 'Anemias por deficiencia de hierro', 'Anemia ferropénica'),
('D51.0', 'Anemia por deficiencia de vitamina B12 debida a deficiencia de factor intrínseco', 'Hematología', 'Anemias megaloblásticas', 'Anemia perniciosa'),
('D51.1', 'Anemia por deficiencia de vitamina B12 debida a absorción selectiva defectuosa de vitamina B12', 'Hematología', 'Anemias megaloblásticas', 'Anemia por déficit B12'),
('D51.9', 'Anemia por deficiencia de vitamina B12, no especificada', 'Hematología', 'Anemias megaloblásticas', 'Anemia megaloblástica'),
('D52.0', 'Anemia por deficiencia de folato dietético', 'Hematología', 'Anemias megaloblásticas', 'Anemia por déficit de ácido fólico'),
('D52.9', 'Anemia por deficiencia de folato, no especificada', 'Hematología', 'Anemias megaloblásticas', 'Anemia por déficit de folatos'),
('D53.9', 'Anemia nutricional, no especificada', 'Hematología', 'Anemias nutricionales', 'Anemia carencial'),
('D58.0', 'Esferocitosis hereditaria', 'Hematología', 'Anemias hemolíticas', 'Anemia hemolítica hereditaria'),
('D59.0', 'Anemia hemolítica autoinmune inducida por fármacos', 'Hematología', 'Anemias hemolíticas adquiridas', 'Anemia hemolítica autoinmune'),
('D59.1', 'Otras anemias hemolíticas autoinmunes', 'Hematología', 'Anemias hemolíticas adquiridas', 'Anemia hemolítica autoinmune'),
('D59.9', 'Anemia hemolítica adquirida, no especificada', 'Hematología', 'Anemias hemolíticas adquiridas', 'Anemia hemolítica'),
('D60.0', 'Aplasia pura adquirida crónica de células rojas', 'Hematología', 'Aplasias medulares', 'Aplasia de serie roja'),
('D61.0', 'Anemia aplástica constitucional', 'Hematología', 'Aplasias medulares', 'Anemia aplástica congénita'),
('D61.1', 'Anemia aplástica inducida por fármacos', 'Hematología', 'Aplasias medulares', 'Anemia aplástica por fármacos'),
('D61.9', 'Anemia aplástica, no especificada', 'Hematología', 'Aplasias medulares', 'Anemia aplástica'),
('D62', 'Anemia aguda posthemorrágica', 'Hematología', 'Anemias agudas', 'Anemia por hemorragia aguda'),
('D63.0', 'Anemia en neoplasias', 'Hematología', 'Anemias secundarias', 'Anemia asociada a cáncer'),
('D63.8', 'Anemia en otras enfermedades crónicas clasificadas en otra parte', 'Hematología', 'Anemias secundarias', 'Anemia de enfermedades crónicas'),
('D64.0', 'Anemia sideroblástica hereditaria', 'Hematología', 'Otras anemias', 'Anemia sideroblástica'),
('D64.9', 'Anemia, no especificada', 'Hematología', 'Otras anemias', 'Anemia no especificada'),
('D68.0', 'Enfermedad de von Willebrand', 'Hematología', 'Trastornos de coagulación', 'Trastorno de coagulación hereditario'),
('D68.1', 'Deficiencia hereditaria del factor VIII', 'Hematología', 'Trastornos de coagulación', 'Hemofilia A'),
('D68.2', 'Deficiencia hereditaria del factor IX', 'Hematología', 'Trastornos de coagulación', 'Hemofilia B'),
('D68.9', 'Defecto de la coagulación, no especificado', 'Hematología', 'Trastornos de coagulación', 'Trastorno de coagulación'),
('D69.0', 'Púrpura alérgica', 'Hematología', 'Trastornos plaquetarios', 'Púrpura de Schönlein-Henoch'),
('D69.3', 'Púrpura trombocitopénica idiopática', 'Hematología', 'Trastornos plaquetarios', 'Púrpura trombocitopénica idiopática'),
('D69.6', 'Trombocitopenia, no especificada', 'Hematología', 'Trastornos plaquetarios', 'Plaquetas bajas'),

-- NEOPLASIAS - Tumores (C00-D49)
('C15.9', 'Tumor maligno del esófago, parte no especificada', 'Oncología', 'Neoplasias digestivas', 'Cáncer de esófago'),
('C16.9', 'Tumor maligno del estómago, parte no especificada', 'Oncología', 'Neoplasias digestivas', 'Cáncer gástrico'),
('C18.9', 'Tumor maligno del colon, parte no especificada', 'Oncología', 'Neoplasias digestivas', 'Cáncer de colon'),
('C20', 'Tumor maligno del recto', 'Oncología', 'Neoplasias digestivas', 'Cáncer rectal'),
('C22.0', 'Carcinoma hepatocelular', 'Oncología', 'Neoplasias hepáticas', 'Cáncer de hígado'),
('C25.9', 'Tumor maligno del páncreas, parte no especificada', 'Oncología', 'Neoplasias pancreáticas', 'Cáncer de páncreas'),
('C34.1', 'Tumor maligno del lóbulo superior, bronquio o pulmón', 'Oncología', 'Neoplasias respiratorias', 'Cáncer de pulmón'),
('C34.9', 'Tumor maligno de parte no especificada de bronquio o pulmón no especificado', 'Oncología', 'Neoplasias respiratorias', 'Cáncer pulmonar'),
('C43.9', 'Melanoma maligno de la piel, sitio no especificado', 'Oncología', 'Neoplasias de piel', 'Melanoma'),
('C44.9', 'Tumor maligno de la piel, sitio no especificado', 'Oncología', 'Neoplasias de piel', 'Cáncer de piel'),
('C50.9', 'Tumor maligno de la mama, parte no especificada', 'Oncología', 'Neoplasias mamarias', 'Cáncer de mama'),
('C53.9', 'Tumor maligno del cuello del útero, parte no especificada', 'Oncología', 'Neoplasias ginecológicas', 'Cáncer cervicouterino'),
('C54.1', 'Tumor maligno del endometrio', 'Oncología', 'Neoplasias ginecológicas', 'Cáncer de endometrio'),
('C56', 'Tumor maligno del ovario', 'Oncología', 'Neoplasias ginecológicas', 'Cáncer de ovario'),
('C61', 'Tumor maligno de la próstata', 'Oncología', 'Neoplasias urológicas', 'Cáncer de próstata'),
('C64', 'Tumor maligno del riñón, excepto pelvis renal', 'Oncología', 'Neoplasias urológicas', 'Cáncer renal'),
('C67.9', 'Tumor maligno de la vejiga urinaria, parte no especificada', 'Oncología', 'Neoplasias urológicas', 'Cáncer de vejiga'),
('C78.0', 'Tumor maligno secundario del pulmón', 'Oncología', 'Metástasis', 'Metástasis pulmonar'),
('C78.7', 'Tumor maligno secundario del hígado y del conducto biliar intrahepático', 'Oncología', 'Metástasis', 'Metástasis hepática'),
('C79.9', 'Tumor maligno secundario de sitio no especificado', 'Oncología', 'Metástasis', 'Metástasis no especificada'),

-- TRASTORNOS MENTALES (F01-F99)
('F10.0', 'Trastornos mentales y del comportamiento debidos al uso de alcohol: intoxicación aguda', 'Psiquiatría', 'Trastornos por alcohol', 'Intoxicación alcohólica'),
('F10.1', 'Trastornos mentales y del comportamiento debidos al uso de alcohol: uso perjudicial', 'Psiquiatría', 'Trastornos por alcohol', 'Abuso de alcohol'),
('F10.2', 'Trastornos mentales y del comportamiento debidos al uso de alcohol: síndrome de dependencia', 'Psiquiatría', 'Trastornos por alcohol', 'Alcoholismo'),
('F20.0', 'Esquizofrenia paranoide', 'Psiquiatría', 'Esquizofrenia', 'Esquizofrenia paranoide'),
('F20.9', 'Esquizofrenia, no especificada', 'Psiquiatría', 'Esquizofrenia', 'Esquizofrenia'),
('F25.9', 'Trastorno esquizoafectivo, no especificado', 'Psiquiatría', 'Trastornos psicóticos', 'Trastorno esquizoafectivo'),
('F31.9', 'Trastorno afectivo bipolar, no especificado', 'Psiquiatría', 'Trastornos del estado de ánimo', 'Trastorno bipolar'),
('F32.0', 'Episodio depresivo leve', 'Psiquiatría', 'Trastornos depresivos', 'Depresión leve'),
('F32.1', 'Episodio depresivo moderado', 'Psiquiatría', 'Trastornos depresivos', 'Depresión moderada'),
('F32.2', 'Episodio depresivo severo sin síntomas psicóticos', 'Psiquiatría', 'Trastornos depresivos', 'Depresión severa'),
('F32.9', 'Episodio depresivo, no especificado', 'Psiquiatría', 'Trastornos depresivos', 'Depresión'),
('F33.9', 'Trastorno depresivo recurrente, no especificado', 'Psiquiatría', 'Trastornos depresivos', 'Depresión recurrente'),
('F40.0', 'Agorafobia', 'Psiquiatría', 'Trastornos de ansiedad', 'Agorafobia'),
('F40.1', 'Fobias sociales', 'Psiquiatría', 'Trastornos de ansiedad', 'Fobia social'),
('F41.0', 'Trastorno de pánico [ansiedad paroxística episódica]', 'Psiquiatría', 'Trastornos de ansiedad', 'Trastorno de pánico'),
('F41.1', 'Trastorno de ansiedad generalizada', 'Psiquiatría', 'Trastornos de ansiedad', 'Ansiedad generalizada'),
('F41.9', 'Trastorno de ansiedad, no especificado', 'Psiquiatría', 'Trastornos de ansiedad', 'Ansiedad'),
('F42', 'Trastorno obsesivo-compulsivo', 'Psiquiatría', 'Trastornos obsesivo-compulsivos', 'TOC'),
('F43.0', 'Reacción a estrés agudo', 'Psiquiatría', 'Trastornos por estrés', 'Estrés agudo'),
('F43.1', 'Trastorno de estrés postraumático', 'Psiquiatría', 'Trastornos por estrés', 'PTSD'),
('F43.2', 'Trastornos de adaptación', 'Psiquiatría', 'Trastornos adaptativos', 'Trastorno adaptativo'),

-- ENFERMEDADES DEL SISTEMA NERVIOSO (G00-G99)
('G00.9', 'Meningitis bacteriana, no especificada', 'Neurología', 'Infecciones del SNC', 'Meningitis bacteriana'),
('G03.9', 'Meningitis, no especificada', 'Neurología', 'Infecciones del SNC', 'Meningitis'),
('G04.9', 'Encefalitis, mielitis y encefalomielitis, no especificadas', 'Neurología', 'Infecciones del SNC', 'Encefalitis'),
('G20', 'Enfermedad de Parkinson', 'Neurología', 'Trastornos del movimiento', 'Parkinson'),
('G25.3', 'Mioclono', 'Neurología', 'Trastornos del movimiento', 'Mioclonías'),
('G30.9', 'Enfermedad de Alzheimer, no especificada', 'Neurología', 'Demencias', 'Alzheimer'),
('G40.0', 'Epilepsia y síndromes epilépticos idiopáticos localizados con crisis de inicio focal', 'Neurología', 'Epilepsia', 'Epilepsia focal'),
('G40.3', 'Epilepsia y síndromes epilépticos idiopáticos generalizados', 'Neurología', 'Epilepsia', 'Epilepsia generalizada'),
('G40.9', 'Epilepsia, no especificada', 'Neurología', 'Epilepsia', 'Epilepsia'),
('G43.0', 'Migraña sin aura [migraña común]', 'Neurología', 'Cefaleas', 'Migraña sin aura'),
('G43.1', 'Migraña con aura [migraña clásica]', 'Neurología', 'Cefaleas', 'Migraña con aura'),
('G43.9', 'Migraña, no especificada', 'Neurología', 'Cefaleas', 'Migraña'),
('G44.0', 'Síndrome de cefalea en racimos y otras cefalalgias trigémino-autonómicas', 'Neurología', 'Cefaleas', 'Cefalea en racimos'),
('G44.2', 'Cefalea de tipo tensional', 'Neurología', 'Cefaleas', 'Cefalea tensional'),
('G45.9', 'Ataque isquémico transitorio, no especificado', 'Neurología', 'Enfermedad cerebrovascular', 'AIT'),
('G46.0', 'Síndrome de la arteria cerebral media', 'Neurología', 'Enfermedad cerebrovascular', 'Síndrome de ACM'),
('G47.0', 'Trastornos del inicio y del mantenimiento del sueño [insomnios]', 'Neurología', 'Trastornos del sueño', 'Insomnio'),
('G47.2', 'Trastornos del ritmo circadiano del sueño', 'Neurología', 'Trastornos del sueño', 'Trastorno del ritmo circadiano'),
('G50.0', 'Neuralgia del trigémino', 'Neurología', 'Neuropatías craneales', 'Neuralgia trigeminal'),
('G51.0', 'Parálisis de Bell', 'Neurología', 'Neuropatías craneales', 'Parálisis facial'),
('G56.0', 'Síndrome del túnel carpiano', 'Neurología', 'Neuropatías periféricas', 'Túnel carpiano'),
('G57.0', 'Lesión del nervio ciático', 'Neurología', 'Neuropatías periféricas', 'Ciática'),
('G60.9', 'Neuropatía hereditaria e idiopática, no especificada', 'Neurología', 'Neuropatías periféricas', 'Neuropatía'),
('G62.9', 'Polineuropatía, no especificada', 'Neurología', 'Neuropatías periféricas', 'Polineuropatía'),

-- ENFERMEDADES DEL OJO Y ANEXOS (H00-H59)
('H00.0', 'Orzuelo y chalazión del párpado', 'Oftalmología', 'Enfermedades de párpados', 'Orzuelo'),
('H10.0', 'Conjuntivitis mucopurulenta', 'Oftalmología', 'Conjuntivitis', 'Conjuntivitis bacteriana'),
('H10.1', 'Conjuntivitis atópica aguda', 'Oftalmología', 'Conjuntivitis', 'Conjuntivitis alérgica'),
('H10.9', 'Conjuntivitis, no especificada', 'Oftalmología', 'Conjuntivitis', 'Conjuntivitis'),
('H16.9', 'Queratitis, no especificada', 'Oftalmología', 'Enfermedades de córnea', 'Queratitis'),
('H25.9', 'Catarata senil, no especificada', 'Oftalmología', 'Cristalino', 'Catarata'),
('H26.9', 'Catarata, no especificada', 'Oftalmología', 'Cristalino', 'Catarata no especificada'),
('H40.0', 'Sospecha de glaucoma', 'Oftalmología', 'Glaucoma', 'Sospecha glaucoma'),
('H40.1', 'Glaucoma primario de ángulo abierto', 'Oftalmología', 'Glaucoma', 'Glaucoma ángulo abierto'),
('H40.9', 'Glaucoma, no especificado', 'Oftalmología', 'Glaucoma', 'Glaucoma'),
('H50.0', 'Esotropía convergente', 'Oftalmología', 'Estrabismo', 'Estrabismo convergente'),
('H52.0', 'Hipermetropía', 'Oftalmología', 'Errores refractivos', 'Hipermetropía'),
('H52.1', 'Miopía', 'Oftalmología', 'Errores refractivos', 'Miopía'),
('H52.2', 'Astigmatismo', 'Oftalmología', 'Errores refractivos', 'Astigmatismo'),
('H53.9', 'Trastorno visual, no especificado', 'Oftalmología', 'Trastornos visuales', 'Trastorno visual'),

-- ENFERMEDADES DEL OÍDO (H60-H95)
('H60.0', 'Otitis externa aguda', 'Otorrinolaringología', 'Oído externo', 'Otitis externa'),
('H60.9', 'Otitis externa, no especificada', 'Otorrinolaringología', 'Oído externo', 'Otitis externa'),
('H65.0', 'Otitis media aguda serosa', 'Otorrinolaringología', 'Oído medio', 'Otitis media serosa'),
('H65.9', 'Otitis media no supurativa, no especificada', 'Otorrinolaringología', 'Oído medio', 'Otitis media'),
('H66.0', 'Otitis media supurativa aguda', 'Otorrinolaringología', 'Oído medio', 'Otitis media aguda'),
('H66.9', 'Otitis media, no especificada', 'Otorrinolaringología', 'Oído medio', 'Otitis media'),
('H69.9', 'Trastorno de la trompa de Eustaquio, no especificado', 'Otorrinolaringología', 'Trompa de Eustaquio', 'Disfunción tubárica'),
('H72.9', 'Perforación de la membrana timpánica, no especificada', 'Otorrinolaringología', 'Membrana timpánica', 'Perforación timpánica'),
('H80.9', 'Otosclerosis, no especificada', 'Otorrinolaringología', 'Oído interno', 'Otosclerosis'),
('H81.0', 'Enfermedad de Ménière', 'Otorrinolaringología', 'Oído interno', 'Enfermedad de Ménière'),
('H81.1', 'Vértigo paroxístico benigno', 'Otorrinolaringología', 'Vértigo', 'Vértigo posicional'),
('H81.9', 'Trastorno de la función vestibular, no especificado', 'Otorrinolaringología', 'Vértigo', 'Vértigo'),
('H90.0', 'Pérdida de la audición conductiva, bilateral', 'Otorrinolaringología', 'Hipoacusia', 'Hipoacusia conductiva'),
('H90.5', 'Pérdida de la audición neurosensorial, no especificada', 'Otorrinolaringología', 'Hipoacusia', 'Hipoacusia neurosensorial'),
('H91.9', 'Pérdida de la audición, no especificada', 'Otorrinolaringología', 'Hipoacusia', 'Hipoacusia'),
('H93.1', 'Tinnitus', 'Otorrinolaringología', 'Síntomas auditivos', 'Acúfenos'),

-- ENFERMEDADES GENITOURINARIAS (N00-N99)
('N00.9', 'Síndrome nefrítico agudo con cambios glomerulares no especificados', 'Nefrología', 'Enfermedades glomerulares', 'Glomerulonefritis aguda'),
('N03.9', 'Síndrome nefrítico crónico con cambios glomerulares no especificados', 'Nefrología', 'Enfermedades glomerulares', 'Glomerulonefritis crónica'),
('N04.9', 'Síndrome nefrótico con cambios glomerulares no especificados', 'Nefrología', 'Enfermedades glomerulares', 'Síndrome nefrótico'),
('N10', 'Nefritis tubulointersticial aguda', 'Nefrología', 'Nefritis intersticial', 'Nefritis aguda'),
('N11.9', 'Nefritis tubulointersticial crónica, no especificada', 'Nefrología', 'Nefritis intersticial', 'Nefritis crónica'),
('N18.1', 'Enfermedad renal crónica, estadio 1', 'Nefrología', 'Enfermedad renal crónica', 'ERC estadio 1'),
('N18.2', 'Enfermedad renal crónica, estadio 2 (leve)', 'Nefrología', 'Enfermedad renal crónica', 'ERC estadio 2'),
('N18.3', 'Enfermedad renal crónica, estadio 3 (moderada)', 'Nefrología', 'Enfermedad renal crónica', 'ERC estadio 3'),
('N18.4', 'Enfermedad renal crónica, estadio 4 (severa)', 'Nefrología', 'Enfermedad renal crónica', 'ERC estadio 4'),
('N18.5', 'Enfermedad renal crónica, estadio 5', 'Nefrología', 'Enfermedad renal crónica', 'ERC estadio 5'),
('N18.6', 'Enfermedad renal en estadio terminal', 'Nefrología', 'Enfermedad renal crónica', 'Enfermedad renal terminal'),
('N18.9', 'Enfermedad renal crónica, no especificada', 'Nefrología', 'Enfermedad renal crónica', 'Enfermedad renal crónica'),
('N20.0', 'Cálculo del riñón', 'Urología', 'Litiasis', 'Cálculo renal'),
('N20.1', 'Cálculo del uréter', 'Urología', 'Litiasis', 'Cálculo ureteral'),
('N20.2', 'Cálculo del riñón con cálculo del uréter', 'Urología', 'Litiasis', 'Litiasis renal'),
('N20.9', 'Cálculo urinario, no especificado', 'Urología', 'Litiasis', 'Litiasis urinaria'),
('N21.0', 'Cálculo en la vejiga', 'Urología', 'Litiasis', 'Cálculo vesical'),
('N30.0', 'Cistitis aguda', 'Urología', 'Infecciones urinarias', 'Cistitis aguda'),
('N30.9', 'Cistitis, no especificada', 'Urología', 'Infecciones urinarias', 'Cistitis'),
('N39.0', 'Infección de vías urinarias, sitio no especificado', 'Urología', 'Infecciones urinarias', 'Infección urinaria'),
('N40', 'Hiperplasia de la próstata', 'Urología', 'Enfermedades prostáticas', 'Hiperplasia prostática'),
('N41.9', 'Enfermedad inflamatoria de la próstata, no especificada', 'Urología', 'Enfermedades prostáticas', 'Prostatitis'),
('N70.9', 'Salpingitis y ooforitis, no especificadas', 'Ginecología', 'Enfermedad inflamatoria pélvica', 'Salpingooforitis'),
('N73.9', 'Enfermedad inflamatoria pélvica femenina, no especificada', 'Ginecología', 'Enfermedad inflamatoria pélvica', 'EIP'),
('N80.9', 'Endometriosis, no especificada', 'Ginecología', 'Endometriosis', 'Endometriosis'),
('N81.1', 'Cistocele', 'Ginecología', 'Prolapsos', 'Cistocele'),
('N81.2', 'Prolapso uterino incompleto', 'Ginecología', 'Prolapsos', 'Prolapso uterino'),
('N85.0', 'Hiperplasia glandular del endometrio', 'Ginecología', 'Trastornos endometriales', 'Hiperplasia endometrial'),
('N92.0', 'Menstruación excesiva y frecuente con ciclo regular', 'Ginecología', 'Trastornos menstruales', 'Menorragia'),
('N92.1', 'Menstruación excesiva y frecuente con ciclo irregular', 'Ginecología', 'Trastornos menstruales', 'Metrorragia'),
('N92.6', 'Menstruación irregular, no especificada', 'Ginecología', 'Trastornos menstruales', 'Irregularidad menstrual'),
('N94.3', 'Síndrome de tensión premenstrual', 'Ginecología', 'Trastornos menstruales', 'Síndrome premenstrual'),
('N94.6', 'Dismenorrea, no especificada', 'Ginecología', 'Trastornos menstruales', 'Dismenorrea'),
('N95.1', 'Estado menopáusico y climatérico de la mujer', 'Ginecología', 'Menopausia', 'Menopausia'),

-- EMBARAZO, PARTO Y PUERPERIO (O00-O9A)
('O00.9', 'Embarazo ectópico, no especificado', 'Obstetricia', 'Embarazo ectópico', 'Embarazo ectópico'),
('O03.9', 'Aborto espontáneo completo o no especificado sin complicación', 'Obstetricia', 'Aborto espontáneo', 'Aborto espontáneo'),
('O08.0', 'Infección genital y pélvica consecutiva a aborto, embarazo ectópico y embarazo molar', 'Obstetricia', 'Complicaciones del aborto', 'Infección post-aborto'),
('O10.9', 'Hipertensión preexistente que complica el embarazo, el parto y el puerperio, no especificada', 'Obstetricia', 'Hipertensión en embarazo', 'Hipertensión gestacional'),
('O14.9', 'Preeclampsia, no especificada', 'Obstetricia', 'Hipertensión en embarazo', 'Preeclampsia'),
('O15.9', 'Eclampsia en el embarazo, parto o puerperio, no especificada', 'Obstetricia', 'Hipertensión en embarazo', 'Eclampsia'),
('O20.0', 'Amenaza de aborto', 'Obstetricia', 'Hemorragia en embarazo temprano', 'Amenaza de aborto'),
('O21.9', 'Vómitos del embarazo, no especificados', 'Obstetricia', 'Náuseas y vómitos', 'Hiperémesis gravídica'),
('O24.9', 'Diabetes mellitus en el embarazo, no especificada', 'Obstetricia', 'Diabetes gestacional', 'Diabetes gestacional'),
('O26.9', 'Afección relacionada con el embarazo, no especificada', 'Obstetricia', 'Otras complicaciones', 'Complicación del embarazo'),
('O32.9', 'Atención materna por presentación anómala del feto, no especificada', 'Obstetricia', 'Malpresentaciones', 'Malpresentación fetal'),
('O42.9', 'Ruptura prematura de membranas, no especificada', 'Obstetricia', 'Ruptura de membranas', 'Ruptura prematura de membranas'),
('O44.9', 'Placenta previa, no especificada', 'Obstetricia', 'Trastornos placentarios', 'Placenta previa'),
('O45.9', 'Desprendimiento prematuro de la placenta, no especificado', 'Obstetricia', 'Trastornos placentarios', 'Abruptio placentae'),
('O47.9', 'Falso trabajo de parto, no especificado', 'Obstetricia', 'Trabajo de parto', 'Falso trabajo de parto'),
('O60.1', 'Trabajo de parto prematuro con parto prematuro', 'Obstetricia', 'Parto prematuro', 'Parto pretérmino'),
('O64.9', 'Trabajo de parto obstruido debido a malposición y malpresentación del feto, no especificadas', 'Obstetricia', 'Distocias', 'Trabajo de parto obstruido'),
('O70.9', 'Desgarro perineal durante el parto, no especificado', 'Obstetricia', 'Traumatismos obstétricos', 'Desgarro perineal'),
('O72.0', 'Hemorragia del tercer período del parto', 'Obstetricia', 'Hemorragia obstétrica', 'Hemorragia postparto'),
('O85', 'Sepsis puerperal', 'Obstetricia', 'Infecciones puerperales', 'Sepsis puerperal'),
('O86.0', 'Infección de herida obstétrica quirúrgica', 'Obstetricia', 'Infecciones puerperales', 'Infección de herida quirúrgica'),
('O87.9', 'Complicación venosa en el puerperio, no especificada', 'Obstetricia', 'Complicaciones vasculares', 'Complicación venosa puerperal'),
('O90.9', 'Complicación del puerperio, no especificada', 'Obstetricia', 'Complicaciones puerperales', 'Complicación puerperal'),

-- ENFERMEDADES DE LA PIEL (L00-L99)
('L00', 'Síndrome de la piel escaldada por estafilococos', 'Dermatología', 'Infecciones cutáneas', 'Síndrome estafilocócico'),
('L01.0', 'Impétigo [cualquier sitio] [cualquier organismo]', 'Dermatología', 'Infecciones cutáneas', 'Impétigo'),
('L02.9', 'Absceso cutáneo, furúnculo y carbunco de sitio no especificado', 'Dermatología', 'Infecciones cutáneas', 'Absceso cutáneo'),
('L03.9', 'Celulitis, no especificada', 'Dermatología', 'Infecciones cutáneas', 'Celulitis'),
('L08.9', 'Infección local de la piel y del tejido subcutáneo, no especificada', 'Dermatología', 'Infecciones cutáneas', 'Infección cutánea'),
('L20.9', 'Dermatitis atópica, no especificada', 'Dermatología', 'Dermatitis', 'Dermatitis atópica'),
('L21.9', 'Dermatitis seborreica, no especificada', 'Dermatología', 'Dermatitis', 'Dermatitis seborreica'),
('L23.9', 'Dermatitis alérgica de contacto, causa no especificada', 'Dermatología', 'Dermatitis', 'Dermatitis alérgica'),
('L24.9', 'Dermatitis de contacto por irritantes, causa no especificada', 'Dermatología', 'Dermatitis', 'Dermatitis por contacto'),
('L25.9', 'Dermatitis de contacto, no especificada, causa no especificada', 'Dermatología', 'Dermatitis', 'Dermatitis de contacto'),
('L30.9', 'Dermatitis, no especificada', 'Dermatología', 'Dermatitis', 'Dermatitis'),
('L40.0', 'Psoriasis vulgar', 'Dermatología', 'Psoriasis', 'Psoriasis vulgar'),
('L40.9', 'Psoriasis, no especificada', 'Dermatología', 'Psoriasis', 'Psoriasis'),
('L50.9', 'Urticaria, no especificada', 'Dermatología', 'Urticaria', 'Urticaria'),
('L60.0', 'Uña encarnada', 'Dermatología', 'Trastornos ungueales', 'Uña encarnada'),
('L70.0', 'Acné vulgar', 'Dermatología', 'Acné', 'Acné vulgar'),
('L70.9', 'Acné, no especificado', 'Dermatología', 'Acné', 'Acné'),
('L72.9', 'Quiste folicular de la piel y del tejido subcutáneo, no especificado', 'Dermatología', 'Quistes cutáneos', 'Quiste sebáceo'),
('L82', 'Queratosis seborreica', 'Dermatología', 'Lesiones benignas', 'Queratosis seborreica'),
('L85.0', 'Ictiosis adquirida', 'Dermatología', 'Trastornos de queratinización', 'Ictiosis'),
('L98.9', 'Trastorno de la piel y del tejido subcutáneo, no especificado', 'Dermatología', 'Otros trastornos', 'Trastorno cutáneo'),

-- PEDIATRÍA - Afecciones originadas en período perinatal (P00-P96)
('P00.9', 'Feto y recién nacido afectados por trastorno materno no especificado', 'Pediatría', 'Afecciones perinatales', 'Afección perinatal materna'),
('P07.0', 'Peso extremadamente bajo al nacer', 'Pediatría', 'Trastornos relacionados con duración corta de gestación', 'Peso extremadamente bajo'),
('P07.1', 'Otros pesos bajos al nacer', 'Pediatría', 'Trastornos relacionados con duración corta de gestación', 'Bajo peso al nacer'),
('P22.0', 'Síndrome de dificultad respiratoria del recién nacido', 'Pediatría', 'Trastornos respiratorios', 'Síndrome de distress respiratorio'),
('P22.9', 'Dificultad respiratoria del recién nacido, no especificada', 'Pediatría', 'Trastornos respiratorios', 'Dificultad respiratoria neonatal'),
('P36.9', 'Sepsis bacteriana del recién nacido, no especificada', 'Pediatría', 'Infecciones perinatales', 'Sepsis neonatal'),
('P39.9', 'Infección específica del período perinatal, no especificada', 'Pediatría', 'Infecciones perinatales', 'Infección perinatal'),
('P59.9', 'Ictericia neonatal, no especificada', 'Pediatría', 'Ictericia neonatal', 'Ictericia del recién nacido'),
('P70.4', 'Otras hipoglicemias neonatales', 'Pediatría', 'Trastornos metabólicos', 'Hipoglicemia neonatal'),
('P81.9', 'Trastorno de la regulación de la temperatura del recién nacido, no especificado', 'Pediatría', 'Trastornos de termorregulación', 'Trastorno térmico neonatal'),
('P92.9', 'Problema de la alimentación del recién nacido, no especificado', 'Pediatría', 'Problemas alimentarios', 'Problema alimentario neonatal'),
('P96.9', 'Afección originada en el período perinatal, no especificada', 'Pediatría', 'Otras afecciones perinatales', 'Afección perinatal');